### ISSUE TITLE
Update to Bootstrap Italia latest version 

### ISSUE THREAD

**Issue by gtico80** [italia/bootstrap-italia-playground#2]
Update the bootstrap italia to the latest version found on public website: 1.2.6 (https://github.com/italia/bootstrap-italia/releases/download/v1.2.6/bootstrap-italia.zip)

**Comment by bfabio** [comment]
Fixed by https://github.com/italia/bootstrap-italia-playground/commit/39d139d84f3ef9df5b7c279371ecbb9461ef8543
