### ISSUE TITLE
Colori generati con contrasto non sufficiente 

### ISSUE THREAD

**Issue by TheoMadCo** [italia/bootstrap-italia-playground#21]
Nel [fork](https://github.com/TheoMadCo/bootstrap-italia-playground-color-testing) ad hoc che ho creato, presento un esempio di come vengono generati i colori della pagina . Inserito un colore primario che ci si aspetterebbe vedere correttamente nel resto della pagina, in quest'ultima si generano dei contrasti non sufficienti, palesando un comportamento non prevedibile.\
Nel mio caso viene inserito un `primary-color` con valore **hsb(173, 74, 34)** (In HEX: ![#17574f](https://via.placeholder.com/15/17574f/17574f.png) `#17574f`).
Di seguito uno screenshot degli errori.\
<img src="https://i.vgy.me/upIOnz.png" alt="terzo screenshot con errori di contrasto in evidenza">

**Comment by TheoMadCo** [comment]
Il problema può presentarsi anche nei link delle cards e nel footer. Questo perchè si vanno ad assegnare tonalità che vanno a schiarire troppo rispetto al colore primario. Se vengono modificate le seguenti variabili:
- in `_variables.css`, impostare : `$header-slim-bg-color: $primary-a11 !default` ; `$header-center-bg-color: $primary !default` e `$card-link-color: $primary-a9 !default` ;
- in `_footer.css` , impostare : `background-color: $primary-a11;`
si garantisce sempre il corretto contrasto fra sfondo e scritte.

**Comment by astagi** [comment]
@TheoMadCo abbiamo rilasciato una nuova versione di Bootstrap Italia già presente nel playground, fammi sapere come va..
