### ISSUE TITLE
Sembra mancare del codice relativo al carousel

### ISSUE THREAD

**Issue by PiemP** [italia/bootstrap-italia-playground#23]
Buonasera, 

sto verificando il progetto prima di passare da Bootstrap Italia 1.x alla versione 2.x e i file CSS che vengono generati con questo tool hanno parte del codice del carousel mancante e quindi l'elemento non viene reso correttamente.

Grazie e buona serata.

**Comment by PiemP** [comment]
Manca questa direttiva dentro il file `bootstrap-italia.scss`: 

```
// splide carousel
@import '../../node_modules/@splidejs/splide/src/css/core/index';
```

mentre é presente dentro `bootstrap-italia-comuni.scss`.

Non so quali altre differenze si porti dietro il build dei file tramite `rollup` rispetto al build tramite `sass`.

**Comment by astagi** [comment]
@PiemP potresti riprovare con l'ultima versione?

**Comment by PiemP** [comment]
Buongiorno @astagi,

la problematica in questione sembra risolta...purtroppo devo aprire un'altra issue perché ho notato una cosa...devo ancora capire se è relativa al playground o a bootstrap-italia. 

Mi faccio sentire 😉.
