### ISSUE TITLE
"it-header-slim-wrapper it-header-sticky" non funziona

### ISSUE THREAD

**Issue by mancio8** [italia/bootstrap-italia-playground#25]
Provando qualsiasi funzione di stycky trovate sul sito https://italia.github.io/bootstrap-italia/docs/componenti/sticky
ma non ne funziona nessuna

**Comment by astagi** [comment]
@mancio8 perdonami sembra un errore di Bootstrap Italia, potresti verificare l'ultima versione e magari aprire una issue sul repo della libreria?

**Comment by astagi** [comment]
Chiudo per inattività
