### ISSUE TITLE
Mancata corrispondenza del colore impostato nel footer

### ISSUE THREAD

**Issue by abmcr** [italia/bootstrap-italia-playground#28]
Ho seguito l'help, modificando quindi i colori e lanciando npm run build
A seguito di ciò il colore è stato correttamente modificato , ma solo nella testata non nel footer come si vede dall'immagine allegata in cui (visto che la schermata è troppo lungo) si vede chiaramente il bottone nel colore voluto ed il footer sempre bllu
Cosa ho sbagliato? è un bug? Grazie mille

<img width="680" alt="Screenshot 2023-03-25 alle 18 32 58" src="https://user-images.githubusercontent.com/286438/227732664-acfab514-5fb0-4e32-806a-90560f23acfc.png">

**Comment by astagi** [comment]
@abmcr ho aggiornato all'ultima versione di Bootstrap Italia, il problema si presenta ancora?

**Comment by SimoneFalchetti** [comment]
Ora si compila anche se nel file `bootstrap-italia-custom.scss` è *necessario* valorizzare anche le variabili `$footer-top-background` e `$footer-bottom-background`:  
 ```
  // Esempio:
  $primary-h: 0;
  $primary-s: 100;
  $primary-b: 100;
  // Nota: per convertire il codice esadecimale di un colore formato HSB è possibile utilizzare il sito https://rgb.to/.
  $footer-top-background: hsl(210, 12%, 13%); // color-blue-30
  $footer-bottom-background: hsl(208, 12%, 21%); // color-blue-20
  // import libreria
  @import "bootstrap-italia/src/scss/bootstrap-italia.scss";
  ```
**OSS:** per compilare in ambiente Windows, nel file `package.json` sarà necessario modificare la proprietà *vercel* dell'oggetto *scripts*  in questo modo:   
  ```
  "vercel": "rd /s /q \"./bootstrap-italia/\" && xcopy \"node_modules/bootstrap-italia\" \"./bootstrap-italia\" /S /E /H /Y",
  ```
