### ISSUE TITLE
errore in fase di build

### ISSUE THREAD

**Issue by micheleborella** [italia/bootstrap-italia-playground#32]
Quando cerco di fare build (in ambiente windows) mi ritorna il seguente errore
![image](https://github.com/italia/bootstrap-italia-playground/assets/4695831/b7a505a4-53f0-4443-bd45-de9df0bf0a46)

**Comment by antcas92** [comment]
Anche io lo stesso problema. @micheleborella sei riuscito a risolvere?

**Comment by micheleborella** [comment]
@antcas92 purtroppo no

**Comment by CarloSperandeo** [comment]
Ciao, anche io ho riscontrato il tuo problema, ho eseguito il comando di build utilizzando node v.16.20.1

Ho risolto modificando il file package.json riga 7 ed 8 come seguie e quindi il comando npm run build ha funzionato, sembra che sia una questione di percorsi.

```
"build": "npm run vercel && sass --load-path=node_modules scss\\bootstrap-italia-custom.scss:css\\compiled\\bootstrap-italia-custom.min.css --style=compressed",
"vercel": "del .\\bootstrap-italia && recursive-copy -w node_modules\\bootstrap-italia\\ .\\bootstrap-italia",
```
Ciao, buon lavoro

**Comment by micheleborella** [comment]
ok ora funziona, grazie!

**Comment by timetravellerZero** [comment]
errore:
PS C:\Users\victo\OneDrive\Training_Course\NewWorkspace\Bootstrap-Italy\BT_Italy-Project> npm  run
PS C:\Users\victo\OneDrive\Training_Course\NewWorkspace\Bootstrap-Italy\BT_Italy-Project> npm  run
PS C:\Users\victo\OneDrive\Training_Course\NewWorkspace\Bootstrap-Italy\BT_Italy-Project> npm run build
npm ERR! Missing script: "build"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run


qualcuno sa come risolvere?

**Comment by CarloSperandeo** [comment]
@timetravellerZero assicurati di eseguire il comando nella cartella principale dove risiede il file package.json, come vedi dal tuo erroreu prova a digitare npm run per vedere quali comandi sono disponibili (se build è stato configurato nel package.json) inoltre non dimenticare di eseguire prima il comando npm install per scaricare le dipendenze in node_modules.

**Comment by timetravellerZero** [comment]
Grazie mille!

**Comment by chochocaliente** [comment]
dopo aver eseguito npm run build
mi compare questo : Invalid switch - "bootstrap-italia".
il risultato è che non vengono create le cartelle css/compiled e la cartella dist  

ho sbagliato qualcosa?

**Comment by CarloSperandeo** [comment]
Ciao @chochocaliente,
stai eseguendo i comandi dal terminale trovandoti nella cartella del progetto? hai eseguito il comando npm install? stai usando node 16 (node -v il comando)?

Se tutto si, oltre a ricreare le dipendenze eliminando node_modules e rieseguire npm install potresti condividere i log che si generano a seguito di errori nella cartella principale, npm.log o npm-debug.log, potresti anche provare ad eseguire i comandi separatamente (quelli legati a build)

quindi:
- npm run vercel
- sass --load-path=node_modules scss/bootstrap-italia-custom.scss:css/compiled/bootstrap-italia-custom.min.css --style=compressed

puoi verificare l'esistenza di npm.log o npm-debug.log nella directory del progetto (si genera a seguito di errori)...

Facci sapere

**Comment by chochocaliente** [comment]
ciao, 
ho risolto cancellando tutto e ripartendo da zero - anche reinstallando node.js 
non so esattamente quale sia stato il problema ma ho risolto. 
!importante: 
non so per quale motivo la cartella 'dist' non viene più installata, questo crea un problema quando si prova ad importare/usare gli icons in quanto viene descritto un percorso: <svg class="bg-light icon icon-xs icon-padded"><use href="/bootstrap-italia/dist/svg/sprites.svg#it-check-circle"></use></svg> 

cedi che sia un proble in futuro? ho sbagliato qualcosa?  



![Screenshot 2023-09-11 at 09 25 02](https://github.com/italia/bootstrap-italia-playground/assets/144617956/479565b0-9af2-465b-89e1-41374153d413)

**Comment by CarloSperandeo** [comment]
È difficile purtroppo darti una risposta perchè andrebbero visti log, configurazioni etc, quello che mi viene da dirti è di provare con node 16 (provato su mac/win/lnx), anche se non specificata la versione personalmente per questo ed un altro progetto mi sono trovato bene con questa versione, se non lo stai già facendo ti consiglio anche di usare nvm per cambiare al volo le versioni di node e non dover gestirne una installazione alla volta, utile quando hai più progetti.

**Comment by chochocaliente** [comment]
Grazie mille. Sto usando l'ultimo Node però trovo sempre una difficoltà in fase build. questa volta l'errore è questo:

Error: Can't find stylesheet to import.
   ╷
15 │ @import 'node_modules/bootstrap/scss/functions';
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  bootstrap-italia/src/scss/bootstrap-italia.scss 15:9  @import
  scss/bootstrap-italia-custom.scss 15:9                root stylesheet

**Comment by CarloSperandeo** [comment]
Ciao, il problema che stai sottoponendo indica che non viene trovata una directory contenente dei file da importare e ti specifica in quale file c'è il riferimento dove poter intervenire a riga 15.
Chiaramente viene in mente subito di poter fare prove come intervenire sul percorso mettendo una tilde:
@import '~bootstrap/scss/functions'; oppure verificare permessi di scrittura o modificando il codice puntando alla cartella corretta, puoi scaricare a mano bootstrap con npm i bootstrap.

Ma banalmente di consiglio di non sottovalutare l'ipotesi di provare con node 16 perchè il progetto non è di questo anno è probabilmente non hanno usato la 18 e sappiamo che vengono introdotte spesso nuove funzionalità in node non retrocompatibili, ti do questo consiglio rispetto il tuo problema perchè anche io ho riscontrato errori con la 18 e mi è filato tutto liscio con la 16 su windows (con la fix proposta all'inizio del thread) e macos, dai un occhio al tool NVM che ti facilita.

**Comment by chochocaliente** [comment]
Bene passare a node 16 era quello che non volevo fare. Anche perché lavoro su altri progetti che richiedono node 18. Grazie ancora per il supporto.

**Comment by CarloSperandeo** [comment]
Figurati si è trattato di consigli veloci, anche io lavoro su progetti diversi su node, pensa anche vecchi con node 8 per questo diventa indispensabile usare nvm perchè in sostanza digiti all'occorrenza prima di lavorare la versione che ti interessa es 'nvm use 16.20.3' e da solo ti sostituisce la versione node attiva su cui lavorare senza farti perdere tempo nell installare e disinstallare a mano node e perdere anche le configurazioni.
https://github.com/coreybutler/nvm-windows
in bocca al lupo!

**Comment by CarloSperandeo** [comment]
Ciao, anche io vedo che con il tuo codice è antracite anche a me.
Se vedi nel commento viene suggerito di andare sul sito rgb.to, per l'arancione standard ho usato FF6600 (https://rgb.to/ff6600)

Prendi riferimento la riga H S B e mettili nel codice, adesso dovresti vedere l'arancione.
Copia per es. questo codice seguente per #ff6600

$primary-h: 24;
$primary-s: 100;
$primary-b: 100;

Nella mia esperienza una volta soddisfatto con il colore, copi il css nel tuo progetto di destinazione e non ho dovuto fare null'altro.

**Comment by chochocaliente** [comment]
Perfetto! infatti l'ha fatto. Il problema erano le maledette ''cache'' dopo averle cancellate, tutto si è modificato. Ora però sto lavorando su un altro progetto. ma dopo aver fatto npm install ->. va tutto bene e si installa, tuttavia quando provo  a dare   npm run build mi da errore e non si crea la cartella **dist**  -> questo mi sta facendo impazzire. 

vic@vics-MacBook-Pro Project-zero % npm run build
npm ERR! Missing script: "build"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vic/.npm/_logs/2023-09-19T10_19_38_309Z-debug-0.log
vic@vics-MacBook-Pro Project-zero % 



log:
0 verbose cli /Users/vic/.nvm/versions/node/v16.20.2/bin/node /Users/vic/.nvm/versions/node/v16.20.2/bin/npm
1 info using npm@8.19.4
2 info using node@v16.20.2
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 3ms
5 timing config:load:file:/Users/vic/.nvm/versions/node/v16.20.2/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/vic/Desktop/N-PROJECT/Project-zero/.npmrc Completed in 0ms
10 timing config:load:project Completed in 16ms
11 timing config:load:file:/Users/vic/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/Users/vic/.nvm/versions/node/v16.20.2/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 25ms
19 timing npm:load:configload Completed in 25ms
20 timing npm:load:mkdirpcache Completed in 2ms
21 timing npm:load:mkdirplogs Completed in 1ms
22 verbose title npm run build
23 verbose argv "run" "build"
24 timing npm:load:setTitle Completed in 26ms
25 timing config:load:flatten Completed in 5ms
26 timing npm:load:display Completed in 7ms
27 verbose logfile logs-max:10 dir:/Users/vic/.npm/_logs
28 verbose logfile /Users/vic/.npm/_logs/2023-09-19T10_19_38_309Z-debug-0.log
29 timing npm:load:logFile Completed in 8ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 70ms
33 silly logfile start cleaning logs, removing 1 files
34 silly logfile done cleaning log files
35 timing command:run Completed in 8ms
36 verbose stack Error: Missing script: "build"
36 verbose stack
36 verbose stack To see a list of scripts, run:
36 verbose stack   npm run
36 verbose stack     at RunScript.run (/Users/vic/.nvm/versions/node/v16.20.2/lib/node_modules/npm/lib/commands/run-script.js:98:13)
36 verbose stack     at async module.exports (/Users/vic/.nvm/versions/node/v16.20.2/lib/node_modules/npm/lib/cli.js:78:5)
37 verbose cwd /Users/vic/Desktop/N-PROJECT/Project-zero
38 verbose Darwin 22.6.0
39 verbose node v16.20.2
40 verbose npm  v8.19.4
41 error Missing script: "build"
41 error
41 error To see a list of scripts, run:
41 error   npm run
42 verbose exit 1
43 timing npm Completed in 99ms
44 verbose code 1
45 error A complete log of this run can be found in:
45 error     /Users/vic/.npm/_logs/2023-09-19T10_19_38_309Z-debug-0.log

**Comment by CarloSperandeo** [comment]
stai eseguendo il comando npm build da:
/Users/vic/Desktop/N-PROJECT/Project-zero
verifica innanzi tutto che da questo percorso sia presente il file package.json (comando ll) in quanto è nel file package.json che sono definiti i comandi praticabili sotto 'scipts'.

Se esiste e ti trovi nella cartella giusta allora non è definito build, apri package.json e vedi in scripts quali sono i comandi definiti se soddisfano le tue esigenze altrimenti dovrai chiedere agli autori

**Comment by chochocaliente** [comment]
controllato, nel package.json i commandi definiti sono solo: {
  "dependencies": {
    "bootstrap-italia": "^1.6.4"
  }
}

**Comment by ruda76** [comment]
Buongiorno, quando provo a fare la build ottengo il seguente errore:

/var/www/html/bootstrap-italia-playground-main/node_modules/del-cli/cli.js:2
import process from 'node:process';
       ^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bootstrap-italia-playground@2.0.0 vercel: `del .\bootstrap-italia && recursive-copy -w node_modules\bootstrap-italia\ .\bootstrap-italia`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bootstrap-italia-playground@2.0.0 vercel script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-09-22T09_27_12_580Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bootstrap-italia-playground@2.0.0 build: `npm run vercel && sass --load-path=node_modules scss\bootstrap-italia-custom.scss:css\compiled\bootstrap-italia-custom.min.css --style=compressed`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bootstrap-italia-playground@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-09-22T09_27_12_597Z-debug.log


Potete aiutarmi?

Grazier

**Comment by chochocaliente** [comment]
?

**Comment by ruda76** [comment]
Sto provando a cambiare i colori del progetto playground, seguendo le istruzioni ho modificato il file scss/bootstrap-italia-custom.scss e poi eseguito il comando npm run build.
L'errore è quello riportato nel precedente messaggio.

Grazie

**Comment by astagi** [comment]
Il thread viene chiuso perchè sono riportati diversi problemi su playground nello stesso thread, vi chiedo di provare a utilizzare Node dalla 18 in su e aggiornare il playground all'ultima versione. Se i problemi persistono si prega di aprire una issue dedicata. Grazie!

**Comment by astagi** [comment]
@CarloSperandeo riprendo questo vecchio thread in quanto mi è stato segnalato in community. Suggerirei di utilizzare il terminale [WSL](https://learn.microsoft.com/en-us/windows/wsl/install) per non dover cambiare le path ogni volta. Adesso abbiamo una nuova versione compatibile con Node 18.x. Attendo vostri feedback grazie! @chochocaliente @ruda76 @timetravellerZero @antcas92 @micheleborella

**Comment by CarloSperandeo** [comment]
Ciao @astagi, grazie innanzi tutto, sono indicazioni che ampliano, hai fatto bene. Ho suggerito la 16 in precedenza perchè indicata su un progetto analogo per generare i template html comuni e mi trovai bene.
Ne approfitto anche come feedback per dirti che usando node 18 e seguendo la guida del progetto sul readme, funziona tutto senza alcun problema, terrò a mente anche wsl che già conoscevo ma non avevo pensato come suggerimento, grazie.

**Comment by astagi** [comment]
Ottimo! Grazie del feedback @CarloSperandeo !
