### ISSUE TITLE
Non funziona l'aggiornamento automatico della libreria

### ISSUE THREAD

**Issue by zetareticoli** [italia/bootstrap-italia-playground#46]
## Comportamento atteso

Il workflow "Bootstrap Italia update" fallisce sempre.

## Comportamento attuale

Il workflow dovrebbe funzionare correttamente per consentire l'aggiornamento automatico della libreria.

**Comment by Fupete** [comment]
@astagi puoi verificare l'azione perché non va a buon fine? 

ps. c'è qualche componente in index.html forse che ha markup datato? Da verificare (senza priorità)
